### ISSUE TITLE
Websocket errors with nginx

### ISSUE THREAD

**Issue by drlauridsen** [gotify/server#341]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.
- [x] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ ] Docker
- [x] Linux native platform
- [ ] Windows native platform

**Describe your problem**
Despite following the instructions for nginx in the gotify docs, and several nginx docs, I still experience websocket errors in the android client.
It seems to be working fine, messages received as they should, but a lot of errors as seen in below log..
my nginx config is ...
<details><summary>Nginx config</summary><br><pre>
server {
        listen 80;
        server_name  myservername;
        return 301 https://myservername$request_uri;
    }
    server {
        listen 443 ssl;
        server_name  myservername;
        include ssl.conf;
        location / {
        proxy_pass http://x.x.x.x:8090;
        proxy_http_version 1.1;
        # Ensuring it can use websockets
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;                      proxy_set_header   X-Forwarded-Proto http;
        proxy_redirect     http:// $scheme://;
# The proxy must preserve the host because gotify verifies the host with th>        # for WebSocket connections
        proxy_set_header   Host $http_host;
        # These sets the timeout so that the websocket can stay alive
        proxy_connect_timeout   7m;
        proxy_send_timeout      7m;
        proxy_read_timeout      7m;
} }
</pre></details>

**Any errors, logs, or other information that might help us identify your problem**

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.

<details><summary>Log from android app</summary><br><pre>
2020-07-16T10:35:36.194Z ERROR: cannot retrieve missing messages
Code(401) Response: {"error":"Unauthorized","errorCode":401,"errorDescription":"you need to provide a valid access token or user credentiaHej Steph to access this api"}
	at com.github.gotify.api.Api.execute(Api.java:15)
	at com.github.gotify.MissedMessageUtil.missingMessages(MissedMessageUtil.java:46)
	at com.github.gotify.service.WebSocketService.notifyMissedNotifications(WebSocketService.java:141)
	at com.github.gotify.service.WebSocketService.lambda$ugKzrAYeAFU2vbgZGvvC9ediB8A(Unknown Source:0)
	at com.github.gotify.service.-$$Lambda$WebSocketService$ugKzrAYeAFU2vbgZGvvC9ediB8A.run(Unknown Source:2)
	at com.github.gotify.service.WebSocketConnection$Listener.onOpen(WebSocketConnection.java:141)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:210)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

2020-07-16T10:35:36.084Z INFO: WebSocket: opened
2020-07-16T10:35:35.966Z INFO: WebSocket: starting...
2020-07-16T10:34:38.642Z INFO: WebSocket: opened
2020-07-16T10:34:38.570Z WARN: WebSocket: closed
2020-07-16T10:34:38.548Z INFO: WebSocket: starting...
2020-07-16T10:34:38.546Z INFO: WebSocket: closing existing connection.
2020-07-16T10:34:36.312Z INFO: WebSocket: opened
2020-07-16T10:34:35.963Z INFO: WebSocket: scheduling a restart in 60 second(s)
2020-07-16T10:34:35.951Z ERROR: WebSocket: failure  Message: 
java.io.IOException: closed
	at okhttp3.internal.ws.WebSocketWriter.writeControlFrame(WebSocketWriter.java:113)
	at okhttp3.internal.ws.WebSocketWriter.writePing(WebSocketWriter.java:76)
	at okhttp3.internal.ws.RealWebSocket.writePingFrame(RealWebSocket.java:553)
	at okhttp3.internal.ws.RealWebSocket$PingRunnable.run(RealWebSocket.java:530)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

2020-07-16T10:34:35.508Z INFO: Entering LogsActivity
2020-07-16T10:34:33.650Z INFO: Loading more messages for -1
2020-07-16T10:34:33.634Z INFO: Entering MessagesActivity
2020-07-16T10:34:33.570Z INFO: Server version: 2.0.16@2020-05-09-16:00:37
2020-07-16T10:34:33.545Z INFO: WebSocket: scheduling a restart in 5 second(s)
2020-07-16T10:34:33.545Z INFO: Network reconnected
2020-07-16T10:34:33.477Z INFO: WebSocket: starting...
2020-07-16T10:34:33.468Z INFO: Starting WebSocketService
2020-07-16T10:34:33.467Z INFO: WebSocket: closing existing connection.
2020-07-16T10:34:33.456Z INFO: Authenticated as username
2020-07-16T10:34:33.149Z INFO: Entering InitializationActivity
2020-07-16T09:27:12.193Z INFO: Loading more messages for -1
2020-07-16T09:27:12.150Z INFO: Entering MessagesActivity
2020-07-16T04:45:44.136Z INFO: WebSocket: received message {"id":73,"appid":2,"message":"Bevægelse","title":"Bevægelse","priority":8,"date":"2020-07-16T06:45:40.228768461+02:00"}

2020-07-16T02:03:58.826Z INFO: WebSocket: received message {"id":72,"appid":2,"message":"Bevægelse","title":"Bevægelse","priority":8,"date":"2020-07-16T04:03:55.450012057+02:00"}
</pre></details>

**Comment by jmattheis** [comment]
Does this issue appear on the webui / on your phone when connected to Wi-Fi?
The errors look like normal network errors that can occur while on mobile internet.

**Comment by drlauridsen** [comment]
> 
> 
> Does this issue appear on the webui / on your phone when connected to Wi-Fi?
> The errors look like normal network errors that can occur while on mobile internet.

Havent tried with the webui. But it occurs when connected to wifi at home..

**Comment by jmattheis** [comment]
Could you show logs with failing connections when on wifi?

**Comment by drlauridsen** [comment]
Not sure I understand what log you want..? The one in the first post, is from when the phone is connnected with Wi-Fi at home..

**Comment by jmattheis** [comment]
I need the logs from gotify/server and the android app.
