### ISSUE TITLE
How can one actually build a working plugin?

### ISSUE THREAD

**Issue by johanfleury** [gotify/server#375]
**Have you read the documentation?**

Yes, but it does not include related information regarding my question.

**You are setting up gotify in**

Docker

**Describe your problem**

I’m trying to write a plugin to interface some tool with Gotify, but I’m unable to load even the simplest plugin due endless issues with go modules versions not matching.

At first I got an error with `github.com/go-playground/validator/v10`’s version, then it was with `github.com/golang/protobuf/proto` then with some `internal` package. I fixed this by copying the relevant lines from this project’s `go.mod` to my plugin’s `go.mod`, but it doesn’t feel like the right thing to do.

I feel like there’s something missing in the build steps regarding modules versions synchronization.

**Any errors, logs, or other information that might help us identify your problem**

Here is a build of the [plugin template](https://github.com/gotify/plugin-template) that didn’t work.

```
$ export LC_ALL=C

$ git clone https://github.com/gotify/plugin-template.git
Cloning into 'plugin-template'...
remote: Enumerating objects: 62, done.
remote: Total 62 (delta 0), reused 0 (delta 0), pack-reused 62
Receiving objects: 100% (62/62), 12.90 KiB | 2.58 MiB/s, done.
Resolving deltas: 100% (27/27), done.

$ cd plugin-template

$ make GOTIFY_VERSION=v2.0.20 download-tools build-linux-amd64
GO111MODULE=off go get -u github.com/gotify/plugin-api/cmd/gomod-cap
mkdir -p ./build || true
rm ./build/gotify-server-go-version || true
rm: cannot remove './build/gotify-server-go-version': No such file or directory
wget -LO ./build/gotify-server-go-version https://raw.githubusercontent.com/gotify/server/v2.0.20/GO_VERSION
--2020-12-20 14:25:31--  https://raw.githubusercontent.com/gotify/server/v2.0.20/GO_VERSION
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7 [text/plain]
Saving to: './build/gotify-server-go-version'

./build/gotify-server-go-version                     100%[======================================================================================================================>]       7  --.-KB/s    in 0s

2020-12-20 14:25:33 (136 KB/s) - './build/gotify-server-go-version' saved [7/7]

wget -LO ./build/gotify-server.mod https://raw.githubusercontent.com/gotify/server/v2.0.20/go.mod
--2020-12-20 14:25:33--  https://raw.githubusercontent.com/gotify/server/v2.0.20/go.mod
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1502 (1.5K) [text/plain]
Saving to: './build/gotify-server.mod'

./build/gotify-server.mod                            100%[======================================================================================================================>]   1.47K  --.-KB/s    in 0s

2020-12-20 14:25:33 (8.07 MB/s) - './build/gotify-server.mod' saved [1502/1502]

gomod-cap -from ./build/gotify-server.mod -to go.mod
2020/12/20 14:25:33 Found common import path github.com/gin-gonic/gin
2020/12/20 14:25:33 Changing require version to v1.6.3
2020/12/20 14:25:33 Found common import path github.com/gotify/plugin-api
2020/12/20 14:25:33 Found common import path github.com/stretchr/testify
2020/12/20 14:25:33 Changing require version to v1.5.1
rm ./build/gotify-server.mod || true
go mod tidy
docker run --rm -v "$PWD/.:/proj" -v "`go env GOPATH`/pkg/mod/.:/go/pkg/mod:ro" -w /proj gotify/build:`cat ./build/gotify-server-go-version`-linux-amd64 go build -mod=readonly -a -installsuffix cgo -ldflags "$LD_FLAGS" -buildmode=plugin  -o ./build/myplugin-linux-amd64.so /proj

$ docker run --rm -it -u 65534:65534 --read-only -v $(pwd)/data/images:/data/images -v $(pwd)/data/db:/data/db/ -v $(pwd)/build/myplugin-linux-amd64.so:/data/plugins/myplugin.so -e GOTIFY_UPLOADEDIMAGESDIR=/data/images -e GOTIFY_PLUGINSDIR=/data/plugins -e GOTIFY_SERVER_PORT=8080 -e GOTIFY_DATABASE_CONNECTION=/data/db/gotify.db gotify/server:2.0.20
Starting Gotify version 2.0.20@2020-10-06-18:29:43
panic: error while loading plugin myplugin.so: plugin.Open("/data/plugins/myplugin"): plugin was built with a different version of package github.com/go-playground/validator/v10

goroutine 1 [running]:
github.com/gotify/server/v2/router.Create(0xc0000115e0, 0xc0004eee40, 0xc0004ca180, 0x12, 0xc000451d50)
        /proj/router/router.go:46 +0x3369
main.main()
        /proj/app.go:51 +0x385

$ # Editing go.mod

$ git diff go.mod
diff --git a/go.mod b/go.mod
index 7e04963..3abeafc 100644
--- a/go.mod
+++ b/go.mod
@@ -1,7 +1,10 @@
 module github.com/gotify/plugin-template

+go 1.15
+
 require (
-       github.com/gin-gonic/gin v1.3.0
+       github.com/gin-gonic/gin v1.6.3
        github.com/gotify/plugin-api v1.0.0
-       github.com/stretchr/testify v1.3.0
+       github.com/stretchr/testify v1.5.1
+       github.com/go-playground/validator/v10 v10.3.0
 )

$ make GOTIFY_VERSION=v2.0.20 download-tools build-linux-amd64                                                                                                                    GO111MODULE=off go get -u github.com/gotify/plugin-api/cmd/gomod-cap
mkdir -p ./build || true
rm ./build/gotify-server-go-version || true
wget -LO ./build/gotify-server-go-version https://raw.githubusercontent.com/gotify/server/v2.0.20/GO_VERSION
--2020-12-20 14:28:49--  https://raw.githubusercontent.com/gotify/server/v2.0.20/GO_VERSION
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7 [text/plain]
Saving to: './build/gotify-server-go-version'

./build/gotify-server-go-version
100%[======================================================================================================================>]       7  --.-KB/s    in 0s

2020-12-20 14:28:50 (199 KB/s) - './build/gotify-server-go-version' saved [7/7]

wget -LO ./build/gotify-server.mod https://raw.githubusercontent.com/gotify/server/v2.0.20/go.mod
--2020-12-20 14:28:50--  https://raw.githubusercontent.com/gotify/server/v2.0.20/go.mod
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1502 (1.5K) [text/plain]
Saving to: './build/gotify-server.mod'

./build/gotify-server.mod
100%[======================================================================================================================>]   1.47K  --.-KB/s    in 0s

2020-12-20 14:28:50 (7.56 MB/s) - './build/gotify-server.mod' saved [1502/1502]

gomod-cap -from ./build/gotify-server.mod -to go.mod
2020/12/20 14:28:50 Found common import path github.com/gin-gonic/gin
2020/12/20 14:28:50 Found common import path github.com/gotify/plugin-api
2020/12/20 14:28:50 Found common import path github.com/stretchr/testify
2020/12/20 14:28:50 Found common import path github.com/go-playground/validator/v10
rm ./build/gotify-server.mod || true
go mod tidy
docker run --rm -v "$PWD/.:/proj" -v "`go env GOPATH`/pkg/mod/.:/go/pkg/mod:ro" -w /proj gotify/build:`cat ./build/gotify-server-go-version`-linux-amd64 go build -mod=readonly -a -installsuffix cgo -ldflags "$LD_FLAGS" -buildmode=plugin  -o ./build/myplugin-linux-amd64.so /proj

$ docker run --rm -it -u 65534:65534 --read-only -v $(pwd)/data/images:/data/images -v $(pwd)/data/db:/data/db/ -v $(pwd)/build/myplugin-linux-amd64.so:/data/plugins/myplugin.so -e GOTIFY_UPLOADEDIMAGESDIR=/data/images -e GOTIFY_PLUGINSDIR=/data/plugins -e GOTIFY_SERVER_PORT=8080 -e GOTIFY_DATABASE_CONNECTION=/data/db/gotify.db gotify/server:2.0.20
Starting Gotify version 2.0.20@2020-10-06-18:29:43
panic: error while loading plugin myplugin.so: plugin.Open("/data/plugins/myplugin"): plugin was built with a different version of package github.com/golang/protobuf/proto

goroutine 1 [running]:
github.com/gotify/server/v2/router.Create(0xc000134228, 0xc000508ae0, 0xc000382f00, 0x12, 0xc000469cd0)
        /proj/router/router.go:46 +0x3369
main.main()
        /proj/app.go:51 +0x385

```

**Comment by jmattheis** [comment]
I've updated https://github.com/gotify/plugin-template. the shared deps of gotify server and a plugin must be exactly the same, otherwise it won't work.

**Comment by johanfleury** [comment]
That was fast, thank you :)

> the shared deps of gotify server and a plugin must be exactly the same, otherwise it won't work.

Yep, that was my understanding too, but then I struggle to understand the purpose of `gomod-cap`.

**Comment by jmattheis** [comment]
gomod-cap only checks the go.mod file and not go.sum, thus, for some deps an explicit version must be stated inside the go.mod file.

**Comment by johanfleury** [comment]
Got it.

i can confirm that my plugin seems to work with the updated `go.mod`.

Thanks again for replying so quickly.
