### ISSUE TITLE
[Help] suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tomamplius** [gotify/server#469]
**Have you read the documentation?**
- [X] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ ] Docker
- [X] Linux native platform
- [ ] Windows native platform

**Describe your problem**
Thanks about your project.
I want compile gotify server but i have an error.
Can you help me to understand the issue?

Test on Debian bullseye with go 16.14, 17.6 and 17.7

step to reproduce : 
~~~
	apt install -y build-essential git wget ca-certificates
	wget -qO - https://deb.nodesource.com/setup_16.x | bash
	wget -qO - https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor  > /usr/share/keyrings/yarnkey.gpg
	echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" > /etc/apt/sources.list.d/yarn.list
	apt-get update
	apt-get install -y nodejs yarn
	wget -qO - https://go.dev/dl/go1.17.7.linux-amd64.tar.gz | tar -C /usr/local -xz
	cd /tmp/
	git clone https://github.com/gotify/server.git
	cd server/
	git checkout v2.1.4
        PATH=${PATH}:/usr/local/go/bin make
~~~
**Any errors, logs, or other information that might help us identify your problem**
~~~
root@thomas-XPS15:/tmp/server# PATH=${PATH}:/usr/local/go/bin make
go test -coverprofile=coverage.txt -covermode=atomic ./...
?   	github.com/gotify/server/v2	[no test files]
ok  	github.com/gotify/server/v2/api	1.633s	coverage: 90.5% of statements
ok  	github.com/gotify/server/v2/api/stream	7.938s	coverage: 99.2% of statements
ok  	github.com/gotify/server/v2/auth	0.095s	coverage: 91.2% of statements
ok  	github.com/gotify/server/v2/auth/password	0.022s	coverage: 100.0% of statements
ok  	github.com/gotify/server/v2/config	0.043s	coverage: 90.9% of statements
ok  	github.com/gotify/server/v2/database	29.767s	coverage: 92.1% of statements
ok  	github.com/gotify/server/v2/docs	0.019s	coverage: 88.9% of statements
ok  	github.com/gotify/server/v2/error	0.022s	coverage: 100.0% of statements
?   	github.com/gotify/server/v2/hack/packr	[no test files]
ok  	github.com/gotify/server/v2/mode	0.009s	coverage: 100.0% of statements
?   	github.com/gotify/server/v2/model	[no test files]
ok  	github.com/gotify/server/v2/plugin	8.390s	coverage: 93.9% of statements
ok  	github.com/gotify/server/v2/plugin/compat	8.633s	coverage: 100.0% of statements
?   	github.com/gotify/server/v2/plugin/example/clock	[no test files]
?   	github.com/gotify/server/v2/plugin/example/echo	[no test files]
?   	github.com/gotify/server/v2/plugin/example/minimal	[no test files]
?   	github.com/gotify/server/v2/plugin/testing/broken/cantinstantiate	[no test files]
?   	github.com/gotify/server/v2/plugin/testing/broken/malformedconstructor	[no test files]
?   	github.com/gotify/server/v2/plugin/testing/broken/noinstance	[no test files]
?   	github.com/gotify/server/v2/plugin/testing/broken/nothing	[no test files]
?   	github.com/gotify/server/v2/plugin/testing/broken/unknowninfo	[no test files]
?   	github.com/gotify/server/v2/plugin/testing/mock	[no test files]
--- FAIL: TestIntegrationSuite (0.02s)
    --- FAIL: TestIntegrationSuite/TestAuthentication (0.01s)
        suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference
            goroutine 8 [running]:
            runtime/debug.Stack()
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
            github.com/stretchr/testify/suite.failOnPanic(0xc000313520)
            	/root/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:63 +0x3e
            panic({0xf182e0, 0x15b2220})
            	/usr/local/go/src/runtime/panic.go:1038 +0x215
            github.com/gotify/server/v2/router.(*IntegrationSuite).AfterTest(0xc000113170, {0x10e1780, 0xc000113170}, {0xf2b020, 0xee2080})
            	/tmp/server/router/router_test.go:50 +0x1d
            github.com/stretchr/testify/suite.Run.func1.1()
            	/root/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:137 +0x1b7
            panic({0xf2e820, 0xc0001df980})
            	/usr/local/go/src/runtime/panic.go:1038 +0x215
            github.com/gotify/server/v2/ui.serveFile({0xfd3b49, 0x10ca260}, {0xfd3006, 0x9}, 0xc0002537f8)
            	/tmp/server/ui/serve.go:44 +0x10d
            github.com/gotify/server/v2/ui.Register(0xc00017fb80, {{0xfcd7aa, 0x5}, {0xfd04ca, 0x7}, {0xfdab9d, 0x13}}, 0x58)
            	/tmp/server/ui/serve.go:28 +0x205
            github.com/gotify/server/v2/router.Create(0xc000119e30, 0xc0001def00, 0xc000178900)
            	/tmp/server/router/router.go:60 +0xbf4
            github.com/gotify/server/v2/router.(*IntegrationSuite).BeforeTest(0xc000113170, {0x10e1780, 0xc000113170}, {0x15d79c0, 0xd0})
            	/tmp/server/router/router_test.go:41 +0x125
            github.com/stretchr/testify/suite.Run.func1(0xc000313520)
            	/root/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:151 +0x26b
            testing.tRunner(0xc000313520, 0xc000507c20)
            	/usr/local/go/src/testing/testing.go:1259 +0x102
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:1306 +0x35a
~~~

**Comment by jmattheis** [comment]
This project kind of misuses make and uses it as task wrapper, so executing make won't actually build the project, only execute some tests. The test fails, because the UI isn't built.

Follow the steps rom https://gotify.net/docs/build to build gotify/server.

**Comment by tomamplius** [comment]
sorry

**Comment by tomamplius** [comment]
Work very well
thanks a lot
~~~
	apt install -y build-essential git wget ca-certificates
	wget -qO - https://deb.nodesource.com/setup_16.x | bash
	wget -qO - https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor  > /usr/share/keyrings/yarnkey.gpg
	echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" > /etc/apt/sources.list.d/yarn.list
apt-get update
apt-get install -y nodejs yarn
wget -qO - https://go.dev/dl/go1.17.7.linux-amd64.tar.gz | tar -C /usr/local -xz
cd /tmp/
git clone https://github.com/gotify/server.git
cd server/
git checkout v2.1.4
PATH=${PATH}:/usr/local/go/bin
export GO111MODULE=on
make download-tools
go get -d
(cd ui && yarn && yarn build)
go run hack/packr/packr.go
go build -ldflags="$LD_FLAGS" -o gotify-server
