### ISSUE TITLE
Setup instructions did not work for me.

### ISSUE THREAD

**Issue by PopeNobody** [gotify/server#471]
**Can the issue be reproduced with the latest available release? (y/n)**
Yes.

**Which one is the environment gotify server is running in?**
- [ ] Docker
- [x ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ x] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [ ] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
I attempted to follow the installation instructions from here:
https://gotify.net/docs/dev-setup

I ran into a couple of issues:

The first was my own ignorance, but the docs could be clearer.  The docs say 

```
If you are in GOPATH, enable [go modules](https://github.com/golang/go/wiki/Modules) explicitly:

$ export GO111MODULE=on
```

I am not a go person, so I did not know if I was "in GOPATH" or not.  I didn't FEEL like I was "in GOPATH'.  I did read the gopath manual page, and concluded that I was not.  But it seemed unclear what to do if I was *NOT* in gopath.  So I set my GOPATH to $HOME/src/go, created $GOPATH/{bin,src,pkg}, and symbolically linked gotify/server to $GOPATH/src/server.

The next command failed for me, though.  I tried it with and without GO111MODULES set to "on".

The result was:

```
parse@copblock:~/src/go/src/server$ export GO111MODULE=on
parse@copblock:~/src/go/src/server$ make download-tools 
go install github.com/go-swagger/go-swagger/cmd/swagger@v0.26.1
can't load package: package github.com/go-swagger/go-swagger/cmd/swagger@v0.26.1: can only use path@version syntax with 'go get'
make: *** [Makefile:41: download-tools] Error 1
parse@copblock:~/src/go/src/server$ unset GO111MODULE 
parse@copblock:~/src/go/src/server$ make download-tools 
go install github.com/go-swagger/go-swagger/cmd/swagger@v0.26.1
can't load package: package github.com/go-swagger/go-swagger/cmd/swagger@v0.26.1: can only use path@version syntax with 'go get'
make: *** [Makefile:41: download-tools] Error 1
parse@copblock:~/src/go/src/server$ 
```

The message from go seemed to suggest that I might have better luck substituting "go get -d" for "go install", and I tried that, but to no avail.

When I tried to run the thing, I saw this:

```
parse@copblock:~/src/go/src/server$ go run .
Starting Gotify version unknown@unknown
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

panic: stat /home/parse/src/go/src/server/ui/build/index.html: no such file or directory

goroutine 1 [running]:
github.com/gotify/server/v2/ui.serveFile(0x1167f26, 0xa, 0x1167496, 0x9, 0xc000523940, 0x1)
        /home/parse/src/go/src/server/ui/serve.go:44 +0x17e
github.com/gotify/server/v2/ui.Register(0xc0000d2140, 0x11656a2, 0x7, 0x11656a2, 0x7, 0x11656a2, 0x7, 0x0)
        /home/parse/src/go/src/server/ui/serve.go:28 +0x213
github.com/gotify/server/v2/router.Create(0xc0000119a8, 0xc00048afc0, 0xc0004f3500, 0xe, 0xc0004bb460)
        /home/parse/src/go/src/server/router/router.go:60 +0xaac
main.main()
        /home/parse/src/go/src/server/app.go:51 +0x3a4
exit status 2
parse@copblock:~/src/go/src/server$ 
```

I was using code that I checked out today, from the master branch, as instructed.

**What did you expect to see?**
I was hoping to see the server run.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
Despair.

**Comment by PopeNobody** [comment]
Incidentally, in case somebody else has this experience, the go manual page suggests reading the go-gopath manual page, but the page you want is actually go-path.

Unless there is another manual page that was missing from my installation.

**Comment by PopeNobody** [comment]
In case anybody is curious:

```
arse@copblock:~/src/go/src/server$ go version
go version go1.13.8 linux/amd64
parse@copblock:~/src/go/src/server$ 
```

**Comment by jmattheis** [comment]
Well this go version is 2.5 years old, you'll need a newer version for this. Build the ui before running `go run .` see https://gotify.net/docs/build

**Comment by PopeNobody** [comment]
I did build the ui, and that seemed to go ok.

I'll go grab the go sources.

Do you suggest checking out a tag/branch of gotify, or is the head generally ready and able?

**Comment by PopeNobody** [comment]
Thanks for the quick response, by the way!

**Comment by jmattheis** [comment]
The master branch should be stable, but if you want to be sure, use the latest tag inside the repository.

**Comment by PopeNobody** [comment]
Ok.  I ended up downloading the binary for now, that worked for me.  None of the easily available versions of go were sufficient to bootstrap go, so I ... uhhh ... let it go.

Got it up and running pretty easily behind nginx.

Gonna try the cli.

Thanks for the help.

Hopefully I'll be able to get it integrated into my android app, and be able to release an FDROID version, push messages were the last thing stopping me.

I'm seeing frequent messages from the web interface saying that the websocket dropped the connection, but it won't do me any harm to see them.  :) 

If you're interested in crowd-sourced emergency response, have a look at cell411.  In an emergency, it sends messages to lots of your friends, and hopefully gets somebody out there to help you that won't shoot you, unlike the cops.

https://getcell411.com/

And thank you for your service.
