### ISSUE TITLE
Cannot log in with nginx proxy (CORS)

### ISSUE THREAD

**Issue by rucksman** [gotify/server#591]
I am running gotify as a docker container since a long time with no problem behind a traefik reverse proxy.

Now I wanted to set up gotify in a docker container on a different server that runs an nginx proxy. Unfortunately I cannot log in:
```
Access to XMLHttpRequest at 'https://mydomain.tld/client' (redirected from 'http://mydomain.tld/client') from origin 'http://mydomain.tld' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
I checked the issues here and found `GOTIFY_SERVER_CORS_ALLOWORIGINS="- .*"`. But when I enter this in my docker-compose file, the docker won't start at all:
```
Starting Gotify version 2.3.0@2023-07-20-18:03:23
panic: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `- .*` into []string

goroutine 1 [running]:
github.com/gotify/server/v2/config.Get()
        /proj/config/config.go:69 +0x226
main.main()
        /proj/app.go:34 +0x21a
```
Any idea how to solve this problem?

**Comment by rucksman** [comment]
I tried a few different ways of entering GOTIFY_SERVER_CORS_ALLOWORIGINS into my docker-compose file, and finally this version worked:
```
- GOTIFY_SERVER_CORS_ALLOWORIGINS=- .*
```
