### ISSUE TITLE
yarn编译报错

### ISSUE THREAD

**Issue by icetech233** [gotify/server#613]
F:\gocode\gotify\server-2.4.0\ui>yarn build
yarn run v1.22.19
$ react-scripts build
C:\Users\yanli\AppData\Roaming\npm\node_modules\react-scripts\node_modules\resolve\lib\sync.js:113
    throw err;
    ^

Error: Cannot find module 'typescript' from 'F:\gocode\gotify\server-2.4.0\ui\node_modules'
    at Function.resolveSync [as sync] (C:\Users\yanli\AppData\Roaming\npm\node_modules\react-scripts\node_modules\resolve\lib\sync.js:111:15)
    at getModules (C:\Users\yanli\AppData\Roaming\npm\node_modules\react-scripts\config\modules.js:119:32)
    at Object.<anonymous> (C:\Users\yanli\AppData\Roaming\npm\node_modules\react-scripts\config\modules.js:142:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\yanli\AppData\Roaming\npm\node_modules\react-scripts\config\webpack.config.js:28:17) {
  code: 'MODULE_NOT_FOUND'
}

Node.js v18.16.1
error Command failed with exit code 1.

**Comment by jmattheis** [comment]
try removing the `ui/node_modules` and run `yarn install` again and then retry the build. If it still doesn't work post the output from both commands.

**Comment by icetech233** [comment]
> try removing the `ui/node_modules` and run `yarn install` again and then retry the build. If it still doesn't work post the output from both commands.

i  use  pnpm install    
yarn build

**Comment by icetech233** [comment]
> try removing the `ui/node_modules` and run `yarn install` again and then retry the build. If it still doesn't work post the output from both commands.

npm install

**Comment by icetech233** [comment]
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...

**Comment by icetech233** [comment]
[1/5] ⠐ puppeteer
[-/5] ⠐ waiting...
[3/5] ⠐ core-js
[-/5] ⠐ waiting...
error F:\gocode\gotify\server\ui\node_modules\puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: F:\gocode\gotify\server\ui\node_modules\puppeteer
Output:
ERROR: Failed to set up Chromium r1036745! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,

**Comment by icetech233** [comment]
yarn  error 


can you  upload  build dic   files

**Comment by jmattheis** [comment]
You have some problems installing dependencies due to connection errors. `yarn build` only works if you've run `yarn install` without errors. Use the prebuild binaries here https://github.com/gotify/server/releases/latest

**Comment by icetech233** [comment]
> binaries
i  need html code

**Comment by najtin** [comment]
@icetech233 Could you explain what it is that you are trying to accomplish? If you want to run the gotify server, then you can either use the binaries, or build the project yourself using the instructions documented here https://gotify.net/docs/build

**Comment by najtin** [comment]
If you only want to obtain the frontend/ui files to serve to the user, run `yarn install` and `yarn build` in the `ui` folder. There you are going to find `build/dist` which contains the files that are served to the user.
