### ISSUE TITLE
npm build error 

### ISSUE THREAD

**Issue by icetech233** [gotify/server#693]
> gotify-ui@0.2.0 build E:\code\gotifyserver\ui
> react-scripts build

Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (E:\code\gotifyserver\ui\node_modules\.pnpm\webpack@4.44.2\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (E:\code\gotifyserver\ui\node_modules\.pnpm\webpack@4.44.2\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (E:\code\gotifyserver\ui\node_modules\.pnpm\webpack@4.44.2\node_modules\webpack\lib\NormalModule.js:471:10)
    at E:\code\gotifyserver\ui\node_modules\.pnpm\webpack@4.44.2\node_modules\webpack\lib\NormalModule.js:503:5
    at E:\code\gotifyserver\ui\node_modules\.pnpm\webpack@4.44.2\node_modules\webpack\lib\NormalModule.js:358:12
    at E:\code\gotifyserver\ui\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\code\gotifyserver\ui\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (E:\code\gotifyserver\ui\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at E:\code\gotifyserver\ui\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (E:\code\gotifyserver\ui\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (E:\code\gotifyserver\ui\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (E:\code\gotifyserver\ui\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (E:\code\gotifyserver\ui\node_modules\.pnpm\enhanced-resolve@4.5.0\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at E:\code\gotifyserver\ui\node_modules\.pnpm\enhanced-resolve@4.5.0\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
E:\code\gotifyserver\ui\node_modules\.pnpm\react-scripts@4.0.3_@types+webpack@4.41.39_eslint@7.32.0_react@16.14.0_sockjs-client@1.6.1_typescript@4.0.2\node_modules\react-scripts\scripts\build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (E:\code\gotifyserver\ui\node_modules\.pnpm\webpack@4.44.2\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (E:\code\gotifyserver\ui\node_modules\.pnpm\webpack@4.44.2\node_modules\webpack\lib\NormalModule.js:417:16)
    at E:\code\gotifyserver\ui\node_modules\.pnpm\webpack@4.44.2\node_modules\webpack\lib\NormalModule.js:452:10
    at E:\code\gotifyserver\ui\node_modules\.pnpm\webpack@4.44.2\node_modules\webpack\lib\NormalModule.js:323:13
    at E:\code\gotifyserver\ui\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\code\gotifyserver\ui\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\code\gotifyserver\ui\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at E:\code\gotifyserver\ui\node_modules\.pnpm\babel-loader@8.1.0_@babel+core@7.12.3_webpack@4.44.2\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v21.7.3
 ELIFECYCLE  Command failed with exit code 1.

**Comment by eternal-flame-AD** [comment]
What's the command you used to build?

**Comment by najtin** [comment]
It seems like you are try to compile gotify/server on bare metal without the container. There is a [stackoverflow post](https://stackoverflow.com/questions/74726224/opensslerrorstack-error03000086digital-envelope-routinesinitialization-e) which suggest to add `NODE_OPTIONS=--openssl-legacy-provider`. Based on the title of #694 it seems like this fixed your issue. 

The [documentation](https://docs.openssl.org/3.0/man7/OSSL_PROVIDER-legacy/) says, that this option enables some legacy methods which are normally not offered anymore. This is an issue with webpack. I am not sure if they are willing to change this. There is a [closed issue from 2021](https://github.com/webpack/webpack/issues/13572) which documents this. In short md4 was moved to the legacy provider in openssl3. MD4 is still the hash function they use on the main branch. 

There is a [monkey patch](https://github.com/webpack/webpack/issues/13572#issuecomment-923736472) to change the algorithm at runtime. I don't know where this is supposed to go. This commit https://github.com/martinpitt/starter-kit/commit/cc075cb6a72100dcf6e84efd0ccb8769502ba8cd#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166fR11 of another project might be helpful. Also i don't know enough about node to tell if this would remove the requirement to add the node option.

**Comment by najtin** [comment]
It seems like this options is automatically in the Makefile if the `node --help` list it in its output. https://github.com/gotify/server/blob/58084c8dea5790796e34540b68d70d4be57395d3/Makefile#L10C1-L10C119. I tested node 22.5.1 and it still has this command in its output.

**Comment by jmattheis** [comment]
Dupe -> #574
